// --- Constants and Configuration ---
const SCRIPT_ID = 'RC-Combo-v6-5-15-debug-log-filter';
const CC_CONSOLE_LOG_LEVEL = 'DEBUG'; // Set to 'DEBUG' for more verbose console logs
const MAX_CHAT_RECORDS = 100;
const RECENTLY_READ_THRESHOLD_MS = 1500;

const SCRIPT_BADGE_COLOR = '#8A2BE2';
const IGNORED_BADGE_COLOR = '#6c757d';
const TOTAL_BADGE_COLOR = '#DC3545';
const NATIVE_BADGE_COLOR = '#F9A825';
const TIMESTAMP_BADGE_COLOR = '#28a745';
const ELAPSED_BADGE_COLOR = '#4a4a4a';
const CC_STORAGE_PREFIX = 'chatCounterCore_gm_';
const CC_STORAGE_COUNTS = CC_STORAGE_PREFIX + 'counts_v6_3';
const UI_VIS_PREFIX = 'ui_visibility_';
const VIS_NATIVE_KEY = UI_VIS_PREFIX + 'native';
const VIS_SCRIPT_KEY = UI_VIS_PREFIX + 'script';
const VIS_TIMESTAMP_KEY = UI_VIS_PREFIX + 'timestamp';
const VIS_ELAPSED_KEY = UI_VIS_PREFIX + 'elapsed';
const VIS_IGNORED_KEY = UI_VIS_PREFIX + 'ignored_v1';
const VIS_TOTAL_KEY = UI_VIS_PREFIX + 'total_v1';
const OVERLAY_POS_X_KEY = 'timestampOverlay_posX';
const OVERLAY_POS_Y_KEY = 'timestampOverlay_posY';
const SORTER_COLLAPSED_KEY = 'sorter_ui_collapsed_v2';
const OVERLAY_SIZE_W_KEY = 'timestampOverlay_sizeW_v1';
const OVERLAY_SIZE_H_KEY = 'timestampOverlay_sizeH_v1';
const RESIZE_DEBOUNCE_MS = 500;
const CC_INJECTED_COUNTER_CLASS = 'rc-combo-injected-counter';
const CC_TIMESTAMP_BADGE_CLASS = 'rc-combo-timestamp-badge';
const CC_ELAPSED_BADGE_CLASS = 'rc-combo-elapsed-badge';
const CC_IGNORED_BADGE_CLASS = 'rc-combo-ignored-badge';
const CC_TOTAL_BADGE_CLASS = 'rc-combo-total-badge';
const CC_BADGE_CONTAINER_CLASS = 'rc-combo-badge-container';
const CC_MARK_ALL_READ_BUTTON_CLASS = 'rc-combo-mark-all-read-button';
const CC_CLEAR_STORAGE_BUTTON_CLASS = 'rc-combo-clear-storage-button';
const HIDE_CLASS_NATIVE = 'rc-combo-hide-native';
const HIDE_CLASS_SCRIPT = 'rc-combo-hide-script';
const HIDE_CLASS_TIMESTAMP = 'rc-combo-hide-timestamp';
const HIDE_CLASS_ELAPSED = 'rc-combo-hide-elapsed';
const HIDE_CLASS_IGNORED = 'rc-combo-hide-ignored';
const HIDE_CLASS_TOTAL = 'rc-combo-hide-total';
const LABEL_SPAN_ID_NATIVE = 'label-span-native';
const LABEL_SPAN_ID_UNIGNORED = 'label-span-unignored';
const LABEL_SPAN_ID_IGNORED = 'label-span-ignored';
const LABEL_SPAN_ID_TIMESTAMP = 'label-span-timestamp';
const LABEL_SPAN_ID_ELAPSED = 'label-span-elapsed';
const LABEL_SPAN_ID_TOTAL = 'label-span-total';
const ELAPSED_UPDATE_INTERVAL_MS = 60 * 1000;
const TIMESTAMP_OVERLAY_UPDATE_INTERVAL_MS = 10 * 1000;

const OBSERVER_TARGET_SELECTOR = 'div[class^="index_chat-list-content-left__"]';
const CLICK_LISTENER_TARGET_SELECTOR = OBSERVER_TARGET_SELECTOR;
const CHAT_TAB_SELECTOR_ALL = 'div[class^="index_chat-list-tab__"]:not([class*="index_chat-list-tab-add__"])';
const NOC_CHAT_CLASS_PART = "index_chat-list-tab-noc__";
const NOC_CHAT_ID = "noc-moderated";
const ACTIVE_CHAT_TAB_SELECTOR = 'div[class*="index_chat-list-tab-active__"]';
const UNREAD_COUNT_SELECTOR = 'div[class^="index_chat-list-unread-count__"]';
const LAST_MESSAGE_CONTAINER_SELECTOR = 'div[class^="index_chat-list-last-message__"]';
const CHAT_TITLE_CONTAINER_SELECTOR = ':scope > div:first-child';
const CHAT_TITLE_CMR_LINK_SELECTOR = 'a[href*="/requests/"]';
const CHAT_TITLE_DESC_SPAN_SELECTOR = 'span';
const STATUS_ICON_SELECTOR = 'div[class^="index_tabStatusIcon__"] span.anticon';
const TITLE_SELECTOR = 'a';

const CUSTOM_PREVIEW_CLASS = 'rc-combo-custom-last-message';
